const ADD_POKEMON = "ADD_POKEMON";
const ADD_POKEMONS = "ADD_POKEMONS";
const CHANGE_FILTER = "CHANGE_FILTER";
const PAGE_LOADED = "PAGE_LOADED";
const POKEMON_PAGE_LOADED = "POKEMON_PAGE_LOADED";

export {
	ADD_POKEMON,
	ADD_POKEMONS,
	CHANGE_FILTER,
	PAGE_LOADED,
	POKEMON_PAGE_LOADED	
}
